# Generated by Django 3.1 on 2021-08-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210823_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CategoryName',
            new_name='categoryName',
        ),
    ]
