# Generated by Django 3.1 on 2021-09-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product_price',
            new_name='productPrice',
        ),
    ]
